GET http://localhost:8000/categorias
###

POST http://localhost:8000/categorias
Content-Type: application/json

{
    "usuario_id": 1,
    "nombre": "Transporte",
    "tipo": "gasto"
}


###

PUT http://localhost:8000/categorias
Content-Type: application/json

{
    "id": 3,
    "usuario_id": 1,
    "nombre": "Alimentación",
    "tipo": "ingreso"
}

###

DELETE http://localhost:8000/categorias
Content-Type: application/json

{
    "id": 2
}

